host: 10.168.215.28
port: 22
user: user
password: "12345678"
remote_dir: /mnt/pod/uploads
out: C:\Users\Malichenko\bl-backup
exclude:
  - .log
  - .tmp
verbose: true

pg_dump:
  enabled: true
  db_host: 10.168.215.28
  db_port: 5432
  db_name: mydb
  db_user: postgres
  db_password: your_password   # опционально; если не указать — .pgpass на VM или PGPASSFILE
  # опционально: /usr/bin/pg_dump, если в PATH другой
  pg_dump_path: pg_dump
  # дополнительные опции pg_dump (список, как есть)
  extra_args:
    - --no-owner
    - --no-privileges