host: 192.168.89.126
port: 22
user: msvb
password: "1qaz@WSX"
remote_dir: /mnt/pod/uploads
# out: C:\Users\Malichenko\bl-backup
exclude:
  - .log
  - .tmp
verbose: true

pg_dump:
  enabled: true
  db_host: 192.168.89.130
  db_port: 5432
  db_name: postgres
  db_user: postgres
  db_password: postgres
  pg_dump_path: pg_dump
  extra_args:
    - --no-owner
    - --no-privileges
