host: 10.168.215.28
port: 22
user: user
password: "12345678"
remote_dir: /mnt/pod/uploads
archive: C:\Users\Malichenko\bl-backup\2025-09-30.zip
strip_top_level: true
verbose: true

db_restore:
  enabled: true
  sql_glob: "*.sql"          
  psql_path: psql            
  db_host: 10.168.215.28
  db_port: 5432
  db_name: postgres
  db_user: postgres
  db_password: postgres
  create_db_if_missing: true
  drop_before: true